### ISSUE TITLE
Some error. Maybe my fault. Help me please.

### ISSUE THREAD

**Issue by dronov-dmitry** [samhogan/Minecraft-Unity3D#6]
Can you help me please
Why this code 
https://github.com/samhogan/Minecraft-Unity3D/blob/d7652f5465a6b3f2d251250a77f8f4caf501f606/Assets/Scripts/TerrainGenerator.cs
return me an error: 
https://prnt.sc/t3i58l
Thx.

**Comment by JohnyDaison** [comment]
Unity is literally telling you what to do. You need to give the FirstScript the prefab you want it to use as the cube by dragging it into the Inspector.

**Comment by dronov-dmitry** [comment]
Thanks a lot i find it.
https://prnt.sc/t49vr7
